### ISSUE TITLE
Builds for different driver versions are not working

### ISSUE THREAD

**Issue by ScottWatsonWork** [gardenlinux/gardenlinux-nvidia-installer#30]
**What happened**:

I am trying to build different driver versions for my gardener machine version 1592.1 and it is failing.

**What you expected to happen**:

I expect the build to work

**How to reproduce it (as minimally and precisely as possible)**:

podman build . --platform=linux/amd64 --build-arg=TARGET_ARCH=amd64 --build-arg=DRIVER_VERSION=495.29.05 --build-arg=GARDENLINUX_VERSION=1592.1

This one didn't work because it seems this version doesn't exist.  

Whereas --build-arg=DRIVER_VERSION=470.82.01 produced a different error 

make[1]: Target 'modules' not remade because of errors.
make[1]: Leaving directory '/usr/src/linux-headers-6.6.47-common'
make: *** [Makefile:80: modules] Error 2
ERROR: The nvidia kernel module was not created.
ERROR: Installation has failed.  Please see the file '/tmp/nvidia/NVIDIA-Linux-x86_64-470.82.01/nvidia-installer.log' for details.  You may find suggestions on fixing installation problems in the README available on the Linux driver download page at www.nvidia.com.
+ exit 1
Error: building at STEP "RUN export KERNEL_NAME=$(./extract_kernel_name.sh ${KERNEL_TYPE} ${TARGET_ARCH}) && ./compile.sh": while running runtime: exit status 1

**Anything else we need to know**:

I am trying to collect all the possible driver versions from this page. 
https://developer.download.nvidia.com/compute/cuda/redist/fabricmanager/linux-x86_64/

As it seems that is where your script download_fabricmanager.sh is able to download the driver versions from based on files that are -archive.tar.xv

It is not clear what driver versions we are able to use as I made the assumption based on the download fabricmanager script.  

**Environment**:
My local env is macbook M2 with podman as my build env.

**Comment by janosbinder** [comment]
Hi @ScottWatsonWork , feel free to reach out me on the company network, and we can debug this issue together.

The fabric manager issue should be resolved now. (We install it via a deb package.)

**Comment by dhague** [comment]
Unfortunately due to the age of NVIDIA drivers in the 400 version range (495.29.05 is over 4 years old) they do not work with modern v6 Linux kernels from Garden Linux 1312 and later. If you want to use a current version of Garden Linux then you will need to use a newer NVIDIA driver.
